### ISSUE TITLE
train.py fails on custom dataset

### ISSUE THREAD

**Issue by Jex-y** [zzh8829/yolov3-tf2#96]
Hi, I am trying to make a number plate detection system as part of a larger system meaning I am training with just one class and on a custom dataset. When I run train.py I get the following output:
```
(yolov3-tf2-gpu) remoteuser@JUSTREADTHEINST C:\Users\remoteuser\code\python\YOLOv3NumberPlate>python train.py --batch_size 8 --dataset C:\Users\remoteuser\code\python\YOLOv3NumberPlate\data\train.tfrecord --val_dataset C:\Users\remoteuse
r\code\python\YOLOv3NumberPlate\data\val.tfrecord --epochs 10 --weights ./checkpoints/yolov3-tiny.tf --tiny --num_classes 1 --classes C:\Users\remoteuser\code\python\YOLOv3NumberPlate\data\class.names
2019-11-10 10:33:11.541539: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2019-11-10 10:33:12.767820: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2019-11-10 10:33:12.836370: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: GeForce GTX 980 major: 5 minor: 2 memoryClockRate(GHz): 1.2155
pciBusID: 0000:01:00.0
2019-11-10 10:33:12.842119: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2019-11-10 10:33:12.846702: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-11-10 10:33:12.850264: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-11-10 10:33:12.856420: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: GeForce GTX 980 major: 5 minor: 2 memoryClockRate(GHz): 1.2155
pciBusID: 0000:01:00.0
2019-11-10 10:33:12.862057: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2019-11-10 10:33:12.866555: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-11-10 10:33:13.376953: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-11-10 10:33:13.380691: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0
2019-11-10 10:33:13.383027: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N
2019-11-10 10:33:13.386374: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2991 MB memory) -> physical GPU (device: 0, name: GeForce GTX 980, pci bus
id: 0000:01:00.0, compute capability: 5.2)
Epoch 1/10
2019-11-10 10:33:21.378911: W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at scatter_nd_op.cc:217 : Invalid argument: indices[0] = [0, 16, 16, 2] does not index into shape [8,13,13,3,6]
2019-11-10 10:33:21.387017: W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Invalid argument: {{function_node __inference_Dataset_map_<lambda>_3384}} [_Derived_]{{function_node __infer
ence_transform_targets_for_output_2947_specialized_for_StatefulPartitionedCall_at___inference_Dataset_map_<lambda>_3384}} {{function_node __inference_transform_targets_for_output_2947_specialized_for_StatefulPartitionedCall_at___inferenc
e_Dataset_map_<lambda>_3384}} indices[0] = [0, 16, 16, 2] does not index into shape [8,13,13,3,6]
         [[{{node TensorScatterUpdate}}]]
         [[StatefulPartitionedCall]]
         [[IteratorGetNext]]
         [[IteratorGetNext/_6]]
2019-11-10 10:33:21.410266: W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Invalid argument: {{function_node __inference_Dataset_map_<lambda>_3384}} [_Derived_]{{function_node __infer
ence_transform_targets_for_output_2947_specialized_for_StatefulPartitionedCall_at___inference_Dataset_map_<lambda>_3384}} {{function_node __inference_transform_targets_for_output_2947_specialized_for_StatefulPartitionedCall_at___inferenc
e_Dataset_map_<lambda>_3384}} indices[0] = [0, 16, 16, 2] does not index into shape [8,13,13,3,6]
         [[{{node TensorScatterUpdate}}]]
         [[StatefulPartitionedCall]]
         [[IteratorGetNext]]
2019-11-10 10:33:21.429166: I tensorflow/core/profiler/lib/profiler_session.cc:184] Profiler session started.
2019-11-10 10:33:21.433674: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cupti64_100.dll'; dlerror: cupti64_100.dll not found
2019-11-10 10:33:21.438715: W tensorflow/core/profiler/lib/profiler_session.cc:192] Encountered error while starting profiler: Unavailable: CUPTI error: CUPTI could not be loaded or symbol could not be found.
      1/Unknown - 5s 5s/stepWARNING:tensorflow:Reduce LR on plateau conditioned on metric `val_loss` which is not available. Available metrics are: lr
W1110 10:33:21.430248  6632 callbacks.py:1824] Reduce LR on plateau conditioned on metric `val_loss` which is not available. Available metrics are: lr
WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are:
W1110 10:33:21.430248  6632 callbacks.py:1250] Early stopping conditioned on metric `val_loss` which is not available. Available metrics are:

Epoch 00001: saving model to checkpoints/yolov3_train_1.tf
2019-11-10 10:33:21.464157: W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at scatter_nd_op.cc:217 : Invalid argument: indices[2] = [2, 9, 15, 2] does not index into shape [8,13,13,3,6]
      1/Unknown - 6s 6s/step2019-11-10 10:33:21.735037: I tensorflow/core/platform/default/device_tracer.cc:588] Collecting 0 kernel records, 0 memcpy records.
2019-11-10 10:33:21.742029: E tensorflow/core/platform/default/device_tracer.cc:70] CUPTI error: CUPTI could not be loaded or symbol could not be found.
Traceback (most recent call last):
  File "train.py", line 180, in <module>
    app.run(main)
  File "C:\Users\remoteuser\.conda\envs\yolov3-tf2-gpu\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Users\remoteuser\.conda\envs\yolov3-tf2-gpu\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "train.py", line 175, in main
    validation_data=val_dataset)
  File "C:\Users\remoteuser\.conda\envs\yolov3-tf2-gpu\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 728, in fit
    use_multiprocessing=use_multiprocessing)
  File "C:\Users\remoteuser\.conda\envs\yolov3-tf2-gpu\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 324, in fit
    total_epochs=epochs)
  File "C:\Users\remoteuser\.conda\envs\yolov3-tf2-gpu\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 123, in run_one_epoch
    batch_outs = execution_function(iterator)
  File "C:\Users\remoteuser\.conda\envs\yolov3-tf2-gpu\lib\site-packages\tensorflow_core\python\keras\engine\training_v2_utils.py", line 86, in execution_function
    distributed_function(input_fn))
  File "C:\Users\remoteuser\.conda\envs\yolov3-tf2-gpu\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 457, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\remoteuser\.conda\envs\yolov3-tf2-gpu\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 520, in _call
    return self._stateless_fn(*args, **kwds)
  File "C:\Users\remoteuser\.conda\envs\yolov3-tf2-gpu\lib\site-packages\tensorflow_core\python\eager\function.py", line 1823, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "C:\Users\remoteuser\.conda\envs\yolov3-tf2-gpu\lib\site-packages\tensorflow_core\python\eager\function.py", line 1141, in _filtered_call
    self.captured_inputs)
  File "C:\Users\remoteuser\.conda\envs\yolov3-tf2-gpu\lib\site-packages\tensorflow_core\python\eager\function.py", line 1224, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager)
  File "C:\Users\remoteuser\.conda\envs\yolov3-tf2-gpu\lib\site-packages\tensorflow_core\python\eager\function.py", line 511, in call
    ctx=ctx)
  File "C:\Users\remoteuser\.conda\envs\yolov3-tf2-gpu\lib\site-packages\tensorflow_core\python\eager\execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError:  {{function_node __inference_Dataset_map_<lambda>_3384}} [_Derived_]{{function_node __inference_transform_targets_for_output_2947_specialized_for_StatefulPartitionedCall_at___
inference_Dataset_map_<lambda>_3384}} {{function_node __inference_transform_targets_for_output_2947_specialized_for_StatefulPartitionedCall_at___inference_Dataset_map_<lambda>_3384}} indices[0] = [0, 16, 16, 2] does not index into shape
[8,13,13,3,6]
         [[{{node TensorScatterUpdate}}]]
         [[StatefulPartitionedCall]]
         [[IteratorGetNext]]
         [[IteratorGetNext/_6]] [Op:__inference_distributed_function_10312]

Function call stack:
distributed_function
```
My dataset build script looks like this if that helps, any advice would be greatly appreciated:
```
import tensorflow as tf
import numpy as np
import os
from PIL import Image
import io
import hashlib

def _bytes_feature(value):
  return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value]))

def _bytes_list_feature(value):
  return tf.train.Feature(bytes_list=tf.train.BytesList(value=value))

def _float_list_feature(value):
  return tf.train.Feature(float_list=tf.train.FloatList(value=value))

def _int64_feature(value):
  return tf.train.Feature(int64_list=tf.train.Int64List(value=[value]))

def _int64_list_feature(value):
  return tf.train.Feature(int64_list=tf.train.Int64List(value=value))

def make_example(file,target_size=(320,320),data_path="data"):
    with open(data_path + "\\" + file,"r") as f:
            data = f.read().split("\n")

    xmin, xmax, ymin, ymax, text, label, diff, trunc, view = [], [], [], [], [], [], [], [], []
    for meta in data:
        if meta != "":
            meta = meta.split("\t")
            imagePath = meta[0]
            x = [float(meta[1]) / target_size[1],
                 float(meta[3]) / target_size[1]]

            y = [float(meta[2]) / target_size[0],
                 float(meta[4]) / target_size[0]]
           
            xmin.append(min(x))
            xmax.append(max(x))
            ymin.append(min(y))
            ymax.append(max(y))

            text.append("numberplate".encode("utf8"))
            label.append(0)
            diff.append(False) # Is object difficult to regocnise e.g. hidden or obstructed
            trunc.append(False) # It the object only partial e.g. person from waist up
            view.append("back".encode("utf8")) # View of the object e.g. behind or infront 

            plate = meta[5]

    image = Image.open(data_path + "\\" + imagePath)
    image.resize(target_size)

    if image.mode in ("RGBA", "LA"):
        background = Image.new(image.mode[:-1], image.size, "black")
        background.paste(image, image.split()[-1])
        image = background

    with io.BytesIO() as output:
        image.save(output,format="jpeg")
        encoded_jpg = output.getvalue()
    
    key = hashlib.sha256(encoded_jpg).hexdigest()  
    encoded_jpg_io = io.BytesIO(encoded_jpg)

    tf_example = tf.train.Example(features=tf.train.Features(feature={
            "image/height"              : _int64_feature(target_size[1]),
            "image/width"               : _int64_feature(target_size[0]),
            "image/filename"            : _bytes_feature(imagePath.encode("utf8")),
            "image/source_id"           : _bytes_feature(imagePath.encode("utf8")),
            "image/key/sha256"          : _bytes_feature(key.encode("utf8")),
            "image/encoded"             : _bytes_feature(encoded_jpg),
            "image/format"              : _bytes_feature("jpg".encode("utf8")),
            "image/object/bbox/xmin"    : _float_list_feature(xmin),
            "image/object/bbox/xmax"    : _float_list_feature(xmax),
            "image/object/bbox/ymin"    : _float_list_feature(ymin),
            "image/object/bbox/ymax"    : _float_list_feature(ymax),
            "image/object/class/text"   : _bytes_list_feature(text),
            "image/object/class/label"  : _int64_list_feature(label),
            "image/object/difficult"    : _int64_list_feature(diff),
            "image/object/truncated"    : _int64_list_feature(trunc),
            "image/object/view"         : _bytes_list_feature(view)
        }))

    return tf_example


def build(output_path,val_or_train="train",data_path="data",target_size=(320,320),val_split=0.2,seed=0):
    np.random.seed(seed)

    files = [ x for x in os.listdir(data_path) if x.split(".")[-1] == "txt"]
    val = np.random.rand(len(files))
    assert val_or_train == "train" or val_or_train == "val"
    
    if val_or_train == "train":
        indexes = np.nonzero(val>=val_split)[0]
    else:
        indexes = np.nonzero(val<val_split)[0]
    num = indexes.shape[0]

    done = 0

    writer = tf.io.TFRecordWriter(output_path)
    for index in indexes:
        tf_example = make_example(files[index],data_path=data_path,target_size=target_size)
        writer.write(tf_example.SerializeToString())
        done += 1
        print("\r{} dataset {:.2f}% Complete\t".format(val_or_train,done*100/num),end="")
    writer.close()
    print("\n")

if __name__ == "__main__":
    build("data\\train.tfrecord","train",data_path="raw_data",target_size=(320,320),val_split=0.2)
    build("data\\val.tfrecord","val",data_path="raw_data",target_size=(320,320),val_split=0.2)
```

**Comment by JeffStodd** [comment]
> Could not load dynamic library 'cupti64_100.dll'; dlerror: cupti64_100.dll not found

I had the same problem fixed it by adding  C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\extras\CUPTI\libx64 to my system path

**Comment by NiklasWilson** [comment]
> Could not load dynamic library 'cupti64_100.dll'; dlerror: cupti64_100.dll not found
I just resolved that but I still have the same problem as the original question

> 2019-11-20 20:32:43.458544: W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at scatter_nd_op.cc:217 : Invalid argument: indices[0] = [0, 24, 23, 1] does not index into shape [1,13,13,3,6]

**Comment by AnaRhisT94** [comment]
The fix to your issue is to to check your annotations. Values bigger than 1 or less than zero cause it.

**Comment by Jex-y** [comment]
> > Could not load dynamic library 'cupti64_100.dll'; dlerror: cupti64_100.dll not found
> 
> I just resolved that but I still have the same problem as the original question
> 
> > 2019-11-20 20:32:43.458544: W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES
> > failed at scatter_nd_op.cc:217 : Invalid argument: indices[0] = [0, 24, 23, 1] does not index into shape [1,13,13,3,6]

@NiklasWilson I found that the issue is resolved if you don't crop the images before and use a larger model size although I have no idea why this is the case.

**Comment by NiklasWilson** [comment]
@Jex-y I am not entirely sure what you mean. All my images are random sizes and aspect ratios. I have done zero cropping or size adjusting of any kind.
Is this required? Are all my images suppose to be uniform size?

I am using a file similar to yours for converting csv to a tfrecord but I always end up with an error like
> does not index into shape

**Comment by Jex-y** [comment]
@NiklasWilson Then i'm not sure whats going on. If your using a model size that is not 416 you may have to go through the source code and edit some of the values as some of them are hard coded.

**Comment by NiklasWilson** [comment]
@Jex-y I resized all my images to 416x416 and than redid the tags. (Didn't fix my problem)
However I think I figured out what you were referring to involving 
> check your annotations. Values bigger than 1 or less than zero

I assume it refers to?
`        'image/object/bbox/xmin': float_list_feature(xmins),
        'image/object/bbox/xmax': float_list_feature(xmaxs),
        'image/object/bbox/ymin': float_list_feature(ymins),
        'image/object/bbox/ymax': float_list_feature(ymaxs),`

As fixing that did get rid of THAT issue :/

**Comment by Jex-y** [comment]
@NiklasWilson At this point I really don't have a clue about what works and why with this code. I managed to fix this error in my code but i'm not sure what did it. Now I have a new error where the Sparse Softmax Cross Entropy with logits fails as there are -1 labels in the data.

**Comment by NiklasWilson** [comment]
@Jex-y If you manage to get it working please do post an update in here, Id very much like to know. Ive managed to get passed these errors but so far I still haven't been able to train a modal that can detect the images it was trained on.

**Comment by zzh8829** [comment]
Looks like you have solved the issue. Please refer to this document https://github.com/zzh8829/yolov3-tf2/blob/master/docs/training_voc.md on transfer learning. I also introduce a dataset visualization tool to help debugging custom dataset issue. If you have further problem please open new tickets
